const employee = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Complete onboarding documents",
        description: "Fill out and submit all onboarding forms.",
        date: "2024-11-16",
        category: "Onboarding",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Team meeting",
        description: "Participate in the weekly team meeting.",
        date: "2024-11-10",
        category: "Meeting",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Set up email filters",
        description: "Organize your inbox with specific email filters.",
        date: "2024-11-18",
        category: "Admin",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Submit project proposal",
        description: "Draft and submit the project proposal.",
        date: "2024-11-12",
        category: "Project",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Code review",
        description: "Review and provide feedback on the latest code changes.",
        date: "2024-11-17",
        category: "Development",
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Create project timeline",
        description: "Develop a timeline for the upcoming project.",
        date: "2024-11-16",
        category: "Planning",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Team retrospective",
        description: "Contribute to the last sprint retrospective.",
        date: "2024-11-13",
        category: "Meeting",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Update documentation",
        description: "Review and update project documentation.",
        date: "2024-11-20",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Fix deployment issues",
        description: "Resolve errors in the production deployment pipeline.",
        date: "2024-11-12",
        category: "Development",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Organize client files",
        description: "Sort and label client-related files for the project.",
        date: "2024-11-18",
        category: "Admin",
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Prepare presentation slides",
        description: "Create slides for the client meeting.",
        date: "2024-11-16",
        category: "Presentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Submit timesheet",
        description: "Submit the weekly timesheet for approval.",
        date: "2024-11-10",
        category: "Admin",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Review bug tickets",
        description: "Analyze and prioritize new bug tickets.",
        date: "2024-11-19",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Conduct training session",
        description: "Deliver a training session for new hires.",
        date: "2024-11-12",
        category: "Training",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Draft project summary",
        description: "Summarize key project milestones.",
        date: "2024-11-21",
        category: "Documentation",
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Organize team outing",
        description: "Plan the itinerary for the team outing.",
        date: "2024-11-16",
        category: "Team Building",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Complete security training",
        description: "Finish the mandatory security training module.",
        date: "2024-11-09",
        category: "Training",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Test API endpoints",
        description: "Verify functionality of updated API endpoints.",
        date: "2024-11-19",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Write test cases",
        description: "Develop test cases for the recent feature release.",
        date: "2024-11-12",
        category: "Testing",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Analyze competitor data",
        description: "Gather and analyze competitor market data.",
        date: "2024-11-18",
        category: "Analysis",
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Schedule code deployment",
        description: "Coordinate and schedule the next code deployment.",
        date: "2024-11-16",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Submit expense report",
        description: "Complete and submit the monthly expense report.",
        date: "2024-11-09",
        category: "Admin",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Perform database backup",
        description: "Backup the project database to prevent data loss.",
        date: "2024-11-18",
        category: "Maintenance",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Resolve client issue",
        description: "Troubleshoot and resolve a client-reported issue.",
        date: "2024-11-12",
        category: "Support",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Optimize website performance",
        description: "Improve website load times and SEO.",
        date: "2024-11-19",
        category: "Development",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employee));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employeesData = JSON.parse(localStorage.getItem("employees"));
  const adminData = JSON.parse(localStorage.getItem("admin"));

  return {
    employeesData,
    adminData,
  };
};
